Team/urls.py
from django.urls import path

from Team.views import team_page, invite_view, accept_view, decline_view, leave_view, create_team_page, \
    notification_page, search_result_team, team_members_page

app_name = "team"
urlpatterns = [
    path('team/<int:my_id>/', team_page, name='team-view'),
    path('team/invite/<int:team_id>/<int:my_id>/', invite_view, name='invite-view'),
    path('accept/<int:my_id>/', accept_view, name='accept-view'),
    path('decline/<int:my_id>/', decline_view, name='decline-view'),
    path('leave/<int:my_id>/', leave_view, name='leave-view'),
    path('team/create/', create_team_page, name='create-team-view'),
    path('notifications/', notification_page, name='notification-view'),
    path('searchteam/', search_result_team, name='search'),
    path('team/<int:my_id>/members/', team_members_page, name='members-view')
    ]

Team/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from AppUser.models import AppUser


class Team(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=80)
    boss = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    members = models.ManyToManyField(AppUser, related_name='members', blank=True)

    def __str__(self):
        return (self.name)

    def get_absolute_url(self):
        return reverse('team:team-view', kwargs={'my_id': self.id})

    def get_join_url(self):
        return reverse('cal:join-view', kwargs={'my_id': self.id})

    def get_leave_url(self):
        return reverse('cal:leave-view', kwargs={'my_id': self.id})

class Request(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user_from = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="user_from")
    user_to = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="user_to")
    date_created = models.DateTimeField(auto_now_add=True)
    date_expired = models.DateTimeField()
    accepted = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)

    def __str__(self):
        return (self.user_to.email + " to " + self.team.name)

    def get_accept_url(self):
        return reverse('team:accept-view', kwargs={'my_id': self.id})

    def get_decline_url(self):
        return reverse('team:decline-view', kwargs={'my_id': self.id})

class Order(models.Model):
    customer = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=80)
    deadline = models.DateTimeField()
    accepted = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)
    market = models.BooleanField(default=False)

    def __str__(self):
        return (self.name + " to " + self.customer.get_full_name)

class Opinion(models.Model):
    OPINION_CHOICES = [(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')]
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    content = models.CharField(blank=True, max_length=250)
    date_created = models.DateTimeField(auto_now_add=True)
    option_1 = models.IntegerField(choices=OPINION_CHOICES)
    option_2 = models.IntegerField(choices=OPINION_CHOICES)
    option_3 = models.IntegerField(choices=OPINION_CHOICES)
    option_4 = models.IntegerField(choices=OPINION_CHOICES)

Team/forms.py
from django import forms
from django.forms import ModelForm

from Team.models import Team


class CreateTeamForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'type': 'text'}))
    description = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Team
        fields = ('name', 'description')

Team/views.py
from datetime import datetime, timedelta

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.http import JsonResponse

# Create your views here.
from django.utils import timezone

from AppUser.models import AppUser
from Team.forms import CreateTeamForm
from Team.models import Team, Request
from django.db.models import Q


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def search_result_user(request):
    if request.accepts('text'):
        res = None
        series = request.POST.get('series')
        querydupa = AppUser.objects.filter(Q(email__icontains=series))
        query_se = querydupa.filter(type="WORKER")
        if len(query_se) > 0 and len(series) > 0:
            data = []
            for pos in query_se:
                item = {
                    'pk': pos.pk,
                    'email': pos.email,
                    'avatar': pos.avatar.url,

                }
                data.append(item)
            res = data
        else:
            res = 'Nie znaleziono pasojacych wynikow'

        return JsonResponse({'data': res})

    return JsonResponse({})


def search_result_team(request):
    if request.accepts('text'):
        res = None
        series = request.POST.get('series')
        query_se = Team.objects.filter(Q(name__icontains=series) | Q(description__icontains=series))
        if len(query_se) > 0 and len(series) > 0:
            data = []
            for pos in query_se:
                item = {
                    'pk': pos.pk,
                    'name': pos.name,
                    'description': pos.description,
                }
                data.append(item)
            res = data
        else:
            res = 'Nie znaleziono pasojacych wynikow'
        print(query_se)
        return JsonResponse({'data': res})
    return JsonResponse({})

def team_members_page(request, my_id):
    obj = get_object_or_404(Team, id=my_id)
    context = {
        'object': obj,
    }
    return render(request, "team_members_view.html", context)

def team_page(request, my_id):
    obj = get_object_or_404(Team, id=my_id)
    context = {
        'object': obj,
    }
    return render(request, "team_view.html", context)


def create_team_page(request):
    form = CreateTeamForm(request.POST or None)
    if form.is_valid():
        new_team = form.save(commit=False)
        new_team.boss = request.user
        new_team.save()
        return redirect(new_team.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, "create_team_view.html", context)


def invite_view(request, team_id, my_id):
    team = get_object_or_404(Team, id=team_id)
    user = get_object_or_404(AppUser, id=my_id)
    date = timezone.now() + timedelta(days=14)
    if team.boss == request.user:
        print("dupa")
        if not team.members.all().contains(user):
            Request.objects.create(user_to=user, user_from=request.user, team=team, date_expired=date)
    return redirect(team.get_absolute_url())


def notification_page(request):
    queryset = Request.objects.filter(user_to=request.user).order_by('-date_created')
    p = Paginator(queryset, 3)
    page_num = request.GET.get("page", 1)
    page = p.page(page_num)
    context = {
        'object_list': page,
    }
    return render(request, "notification_view.html", context)


def accept_view(request, my_id):
    obj = get_object_or_404(Request, id=my_id)
    if request.user == obj.user_to:
        if not obj.accepted and not obj.declined:
            if obj.date_expired > timezone.now():
                obj.accepted = True
                obj.save()
                obj.team.members.add(obj.user_to)
                return redirect(obj.team.get_absolute_url())
    return redirect("/landing/")


def decline_view(request, my_id):
    obj = get_object_or_404(Request, id=my_id)
    if request.user == obj.user_to:
        if not obj.accepted and not obj.declined:
            if obj.date_expired > timezone.now():
                obj.declined = True
                obj.save()
                return redirect("/landing/")
    return redirect("/landing/")


def leave_view(request, my_id):
    obj = get_object_or_404(Team, id=my_id)
    if obj.members.all().contains(request.user):
        obj.members.remove(request.user)
    return redirect("/landing/")

def create_order(request, my_id):
    form = CreateOrderForm(request.POST or None)

Team/templates/create_team_view.html
{%extends 'base.html'%}

{%block content%}
<link rel="stylesheet" href="/static/styles/team_create.css">
<form method="POST">{%csrf_token%}
    {{form.as_p}}
    <button type="submit" class="button_submit" class="">Stwórz</button>
</form>

{%endblock%}

Team/templates/notification_view.html
{%extends 'base.html'%}

{%block content%}

{% for notification in object_list %}
{%if notification.accepted%}
<h4><i class="fa fa-check-circle-o"></i>Accepted</h4>
{%endif%}
{%if notification.declined%}
<h3><i class="fa fa-times-circle-o"></i>Declined</h3>
{%endif%}
<p>{{notification.date_created}}</p>
<h1>
    {{notification.user_from.get_full_name}} invited you to join {{notification.team.name}}
    {%if not notification.declined and not notification.accepted%}
        <a href="{{notification.get_accept_url}}"><i class="fa fa-check"></i></a>
        <a href="{{notification.get_decline_url}}"><i class="fa fa-times"></i></a>
    {%endif%}
</h1>
{% endfor %}

{%if object_list.has_previous%}
<a href="{% url 'team:notification-view' %}?page={{object_list.previous_page_number}}">Back</a>
{%endif%}
{{object_list.number}}
{%if object_list.has_next%}
<a href="{% url 'team:notification-view' %}?page={{object_list.next_page_number}}">Next</a>
{%endif%}
{%endblock%}

Team/templates/team_members_view.html
{%extends 'base.html'%}

{%block content%}
<h1>{{object.name}}</h1>
{% if request.user == object.boss %}
<link rel="stylesheet" href="/static/styles/search.css"/>
 <div class="w-100 text center">
     <form autocomplete="off" id="search-form" method="post">
         {% csrf_token %}
         <input type="text" id="search-input" class="p-3 w-50 search mt-4" placeholder="Search">
     </form>
     <!-- results card -->
     <div id="result-box" class="result-card not-visible">

     </div>
 </div>
<script>
    const sendSearchData = (series) => {
        $.ajax({
            type: 'POST',
            url: '/search/',
            data :{
                'csrfmiddlewaretoken':csrf,
                'series':series,
            },
            success: (res) => {
                const data = res.data
                result_box.innerHTML += "";
                if(Array.isArray(data)){
                    result_box.innerHTML = "";
                    data.forEach(series => {
                        result_box.innerHTML += `
                        <div class='row mt-2 mb-2'>
                            <div class='col-2'>
                                <!-- tu wjebać zdjęcie -->
                                <h5 ${series.avatar}></h5>
                            </div>
                            <div class="col-10">
                                <a href="/profile/${series.pk}">
                                <h5>${series.email}
                                </a>
                                <a href="/team/invite/{{object.pk}}/${series.pk}">+</a></h5>
                            </div>
                        </div>
                        `
                });
            }else{
                if(search_input.value.lenght > 0){
                    result_box.innerHTML = `<b>${data}</b>`
                }
                else{
                result_box.classList.add('not-visible')
                }
            }
        },
        error: (err) => {
            console.log(err);
        }
    })
}
const search_form = document.getElementById('search-form')
const search_input = document.getElementById('search-input')
const result_box = document.getElementById('result-box')
const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value
search_input.addEventListener('keyup', e=>{
    console.log(e.target.value);
    if(result_box.classList.contains('not-visible')){
        result_box.classList.remove('not-visible')
    }
    sendSearchData(e.target.value);
});
</script>
{% endif %}
{% for user in object.members.all %}
<h3>{{user.email}}</h3>
<h5>{{user.get_full_name}}</h5>
{%endfor%}
{%endblock%}

Team/templates/team_view.html
{%extends 'base.html'%}

{%block navbar%}
{%include "navbar.html" %}
{%endblock%}

{%block content%}
<link rel="stylesheet" href="/static/styles/teams.css">

<div class="all_page">
    <div class="col1">
        <div class="t_name">
            <h2>{{object.name}}</h2>
            <h3>{{object.description}}</h3>
        </div>
        <div class="t_members">
            {% for user in object.members.all%}
                <p class="m_name">      <!-- Tu moze byc petla w js -->
                    <a href="{{user.get_absolute_url}}">{{user.get_full_name}}</a>
                </p>
            {%endfor%}
        </div>

    </div>
    <div class="space"></div>
    <div class="col2">
        <div class="c2_content">
            <div class="f_block">
                <p class="f_name">
                    CSSiarz
                </p>
            </div>
            <br><br>
            <div class="d_block">
                <p class="f_desc">
                    CSSuje ile wlezie
                </p>
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>



{%endblock%}