AppUser/urls.py
from django.urls import path

from AppUser.views import logout_view, landing_page, settings_page, \
    profile_page, logister_page, search_page

from Team.views import search_result_user

app_name = "appuser"
urlpatterns = [
    path('logister/', logister_page, name='logister-view'),
    path('logout/', logout_view, name='logout-view'),
    path('landing/', landing_page, name='landing-view'),
    path('settings/', settings_page, name='settings-view'),
    path('profile/<int:my_id>/', profile_page, name='profile-view'),
    path('search_all', search_page, name='search-view'),
    path('search/', search_result_user, name='search'),
    ]

Team/urls.py
from django.urls import path

from Team.views import team_page, invite_view, accept_view, decline_view, leave_view, create_team_page, \
    notification_page, search_result_team, team_members_page

app_name = "team"
urlpatterns = [
    path('team/<int:my_id>/', team_page, name='team-view'),
    path('team/invite/<int:team_id>/<int:my_id>/', invite_view, name='invite-view'),
    path('accept/<int:my_id>/', accept_view, name='accept-view'),
    path('decline/<int:my_id>/', decline_view, name='decline-view'),
    path('leave/<int:my_id>/', leave_view, name='leave-view'),
    path('team/create/', create_team_page, name='create-team-view'),
    path('notifications/', notification_page, name='notification-view'),
    path('searchteam/', search_result_team, name='search'),
    path('team/<int:my_id>/members/', team_members_page, name='members-view')
    ]

bobrzyguy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bobrzyguy import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppUser.urls')),
    path('', include('Team.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UserPage</title>
    {% load static %}
    <link rel="stylesheet" href="/static/styles/style.css"> <! -- glowny css-->
    <link rel="stylesheet" href="/static/styles/footer.css"> <! -- stopka-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width-device-width, initial-scale-1.0">

<!-- Latest compiled and minified JavaScript -->







</head>
<body>
<header>
    <nav>

        {%if request.user.is_authenticated%}
            <h1>Welcome, {{request.user.first_name}} {{request.user.last_name}}</h1>
        {% else %}
            <h1>Hello, Guest </h1>
        {% endif %}
        <ul class="tabs">
            <li class="tab">
                {% if request.user.is_authenticated %}
                <a data-switcher data-tab="1">Wyloguj</a>
                {% else %}
                <a data-switcher data-tab="1">Zaloguj</a>
                {% endif %}
            </li>
            <li class="tab ">
                <a data-switcher data-tab="2">Ogólne</a>
            </li>
            <li class="tab">
                <a data-switcher data-tab="3">Powiadomienia</a>
            </li>
            <li class="tab">
                <a data-switcher data-tab="4">Zespoły</a>
            </li>
        </ul>
 <!--           <li class="search-icon">
            <form method="GET"  action="{% url 'appuser:search-view'%}">
                <input type="search" placeholder="Search"  name="query"  value="{{request.GET.query}}">
                <button class="icon" type="submit">
                    <span class="fas fa-search"></span>
                </button>
            </form>
            </li>   -->
        <div class="w-100 text center">
             <form autocomplete="off" id="search-form-team" method="post">
                 {% csrf_token %}
                 <input type="text" id="search-input-team" class="p-3 w-50 search mt-4" placeholder="Team Search">
             </form>
             <!-- results card -->
             <div id="result-box-team" class="result-card-team not-visible">

             </div>
         </div>

             <!-- JS -->
        <script>
        const sendSearchDataTeam = (series) => {

        $.ajax({
            type: 'POST',
            url: '{% url "team:search" %}',
            data :
            {
                'csrfmiddlewaretoken':csrf2,
                'series':series,
            },
            success: (res) => {
                const data = res.data
                result_box_team.innerHTML += "";
                if(Array.isArray(data)){
                    result_box_team.innerHTML = "";
                    data.forEach(series => {
                        result_box_team.innerHTML += `
                                <a href="/team/${series.pk}" class="link">

                                        <div class="col-10">
                                            <h3>${series.name}</h3>
                                            <h5>${series.description}</h5>
                                        </div>

                                </a>`
                    });
                }else
                    {
                    if(search_input_team.value.lenght > 0){
                        result_box_team.innerHTML = `<b>${data}</b>`
                    }
                    else{
                    result_box_team.classList.add('not-visible')
                    }
                }
            },
            error: (err) => {
                console.log(err);
            }
        })
    }


    const search_form_team = document.getElementById('search-form-team')

    const search_input_team = document.getElementById('search-input-team')

    const result_box_team = document.getElementById('result-box-team')

    const csrf2 = document.getElementsByName('csrfmiddlewaretoken')[0].value

    search_input_team.addEventListener('keyup', e=>{
        console.log(e.target.value);


        if(result_box_team.classList.contains('not-visible')){
            result_box_team.classList.remove('not-visible')
        }

        sendSearchDataTeam(e.target.value);
    });

        </script>











    </nav>
</header>

<screen>
    <section class="pages">
        {%block content%}
            replace me
        {%endblock%}
    </section>
</screen>






<footer>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UserPage</title>
    <link rel="stylesheet" href="styles/style.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<header>
    <nav>
        <h1>Welcome, Nazwa Uzytkownika</h1>
        <ul class="tabs">
            <li class="tab active">
                <a data-switcher data-tab="1">Ogólne</a>
            </li>
            <li class="tab">
                <a data-switcher data-tab="2">Powiadomienia</a>
            </li>
            <li class="tab">
                <a data-switcher data-tab="3">Zespoły</a>
            </li>
        </ul>
    </nav>
</header>

<screen>
    <section class="pages">
        <div class="page">
            <div class="user-column1">
                <a onclick="changeTabs(0)" class="oglist">
                    <i class="fa fa-user"></i>
                </a>
                <a onclick="changeTabs(1)" class="oglist">
                    <i class="fa fa-key"></i>
                </a>
                <a onclick="changeTabs(2)" class="oglist">
                    <i class="fa fa-credit-card"></i>
                </a>
                <a onclick="changeTabs(3)" class="oglist">
                    <i class="fa fa-tasks"></i>
                </a>
                <a onclick="changeTabs(4)" class="oglist">
                    <i class="fa fa-cog"></i>
                </a>
            </div>
            <div class="user-column2">
                <div class="nonEditableSection">
                <img src="images/user.png"/>
                </div>
                <div class="editableSection">
                <div class="general tabShow">
                    <h1><i class="fa fa-user"></i> Edycja danych osobowych:</h1>
                    <h2>Imię</h2><input type="text" class="input" value="Null">
                    <h2>Nazwisko</h2><input type="text" class="input" value="Null">
                    <h2>Email</h2><input type="text" class="input" value="Null">
                    <h2>Password</h2><input type="password" class="input" value="Null">
                    <button class="btn">Save</button>
                </div>
                <div class="password tabShow">
                    <h1><i class="fa fa-credit-card"></i> Zmiana hasła:</h1>
                </div>
                <div class="payment tabShow">
                    <h1><i class="fa fa-credit-card"></i> Edycja ustawień płatności:</h1>
                </div>
                <div class="tasks tabShow">
                    <h1><i class="fa fa-tasks"></i> Lista Zadań:</h1>
                </div>
                <div class="tasks tabShow">
                    <h1><i class="fa fa-cog"></i> Ustawienia Ogólne:</h1>
                </div>
                    </div>
            </div>
        </div>
    </section>
</screen>







    <form method="POST">{% csrf_token %}
        {{form2.as_p}}
        <button type="submit" name="change_last_name">Submit</button>
    </form>

    <form method="POST">{% csrf_token %}
        {{form3.as_p}}
        <button type="submit" name="change_email">Submit</button>
    </form>






<script src="js/functions.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>

</script>
</body>
</html>

<a href="/team/{{object.pk}}/${series.pk}"
                                +</h5>
                                </a>